name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.5'
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Install dependencies
      run: Rscript -e 'install.packages(c("devtools", "testthat", "rcmdcheck"))'
    - uses: r-lib/actions/check-r-package@v2
